# Generated by Django 2.2 on 2021-08-17 17:05

from django.db import migrations, models
import userapi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, upload_to='post_pics')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임 입니다.'}, max_length=15, null=True, unique=True, validators=[userapi.validators.validate_no_special_characters]),
        ),
    ]
