# Generated by Django 2.2 on 2021-08-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('맛집', '맛집'), ('계획', '계획'), ('리뷰', '리뷰'), ('구함', '구함')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
