# Generated by Django 2.2 on 2021-08-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0006_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='p',
        ),
    ]
